### ISSUE TITLE
"Can't use an undefined value as a HASH reference" on cygwin

### ISSUE THREAD

**Issue by Robertof** [dams/io-socket-timeout#3]
Hello,

While using the module [Redis](http://p3rl.org/Redis), which in turn uses this module to implement read/write timeouts, I discovered something wrong (not linked to the `Redis` module).
This is probably strictly platform-related. In your source, there's:

```perl
    if ( $ENV{PERL_IO_SOCKET_TIMEOUT_FORCE_SELECT} ||
         $osname ne 'darwin' && $osname ne 'linux' && $osname ne 'freebsd'
       ) {
```

`$osname` is set to "cygwin" while using cygwin, so `syswrite` and `sysread` are replaced with custom subroutines. The problem is that [here](https://github.com/dams/io-socket-timeout/blob/master/lib/IO/Socket/Timeout.pm#L235) you are calling the `PerlIO::via::Timeout->_fh2prop` method on the filehandle, which *should* return an hash reference containing three values: `timeout_enabled`, `read_timeout` and `write_timeout`. Unfortunately, the method returns `undef` when the file descriptor is not in the `%fd2prop` hash. When does this happen? Well, it happens when the filehandle is not using the `PerlIO::via::Timeout` layer! Infact, when this is the case, the `PUSHED` method is never called and thus `%fd2prop` is never populated with the filehandle.

This is a problem, because the *global* `sysread` (or `syswrite`) is being replaced! So it's not sure whether the filehandle is using the `PerlIO::via::Timeout` layer or not. So, checking if `_fh2prop` returns an `undef` value should be a way to solve the issue, like this:

```perl
            $_prevent_deep_recursion || ! (PerlIO::via::Timeout->_fh2prop($_[0]) || {})->{timeout_enabled}
              and return CORE::sysread($_[0], $_[1], $_[2], $_[3]);
```

(obviously, for `syswrite` too).
However, fixing this issue leads to another one: `sysread`/`syswrite` are called with four arguments, but the functions themselves can be called with less than 4 arguments.

```perl
and return CORE::sysread($_[0], $_[1], $_[2], $_[3]);
```

This causes an "Use of unitialized value in syswrite/sysread" when that is the case. It's trickier to solve, because those functions do not accept `@_` as the argument list. But it should be possible to implement an hackier solution without too many problems. Even disabling `warnings` for a moment could work, like this:

```perl
            {
              no warnings 'uninitialized';
              $_prevent_deep_recursion || ! (PerlIO::via::Timeout->_fh2prop($_[0]) || {})->{timeout_enabled}
                and return CORE::syswrite($_[0], $_[1], $_[2], $_[3]);
            }
```

I'm sorry for the long text. Happy coding!

**Comment by dams** [comment]
Thanks for the report, it's fixed in 0.28
