### ISSUE TITLE
io_sock.t segfaults on Windows

### ISSUE THREAD

**Issue by chorny** [dams/io-socket-timeout#4]
Strawberry 5.20.1.
I tried removing parts of code. This code passes tests:
https://gist.github.com/chorny/8649dd076888b39efcde

**Comment by mishin** [comment]
I support this ticket
I change test 
print "1..13\n";

**Comment by mishin** [comment]
I add PR https://github.com/dams/io-socket-timeout/pull/5

**Comment by dams** [comment]
fixed in 0.32, thanks
